package tfschema

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/enum"
)

var ConsumptionBudget = map[string]*schema.Schema{
	// This isn't an actual field in the API; the true reference is the
	// partition_name_path, and even though Terraform supports resource
	// attribute references, we choose not to use that feature because the
	// partition references would be by index (e.g. partitions[1].partitions[2]
	// instead of "global/gateway/dev"), which would be super unreadable
	// & fragile.
	//
	// So instead, we opt for a coarse reference which acts as a "depends_on"
	// pointer. We validate that the value is the singleton ID of the
	// ConsumptionConfig resource.
	"consumption_config_id": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "ID of the singleton `chronosphere_consumption_config` resource this budget depends on. Acts as an explicit dependency pointer; the actual partition is selected via `partition_slug_path`.",
	},
	"slug": {
		Type:        schema.TypeString,
		Optional:    true,
		Computed:    true,
		ForceNew:    true,
		Description: "Stable identifier for the consumption budget. Generated from `name` if omitted. Immutable after creation.",
	},
	"name": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Display name of the consumption budget. Can be changed after creation.",
	},
	"resource": Enum{
		Value:       enum.ConsumptionBudgetResource.ToStrings(),
		Optional:    true,
		Deprecated:  "use threshold.sku_group and threshold.unit instead",
		Description: "Deprecated: use `threshold.sku_group` and `threshold.unit` instead. Identifies the resource type the budget governs.",
	}.Schema(),
	"partition_slug_path": {
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Forward-slash-delimited path identifying the partition the budget applies to (e.g. `global/gateway/dev`). Must start with the `global` partition slug.",
	},
	"priority": {
		Type:        schema.TypeList,
		Optional:    true,
		Description: "Ordered list of priority rules that classify incoming data. When a drop action runs, higher-numbered priorities (e.g. 10) are dropped first and priority 1 is dropped last. Evaluation stops at the first matching priority.",
		Elem: &schema.Resource{
			Schema: consumptionBudgetPrioritySchema,
		},
	},
	"threshold": {
		Type:        schema.TypeList,
		Optional:    true,
		Description: "Threshold actions to take when budget consumption crosses configured levels.",
		Elem: &schema.Resource{
			Schema: consumptionBudgetThresholdSchema,
		},
	},
	"default_priority": {
		Type:        schema.TypeInt,
		Optional:    true,
		Description: "Priority assigned to requests that do not match any entry in `priority`. Defaults to 10 (dropped first) if unset.",
	},
	"notification_policy_id": {
		Type:        schema.TypeString,
		Optional:    true,
		Description: "ID of the notification policy used to route alerts generated by `ALERT_WARN`/`ALERT_CRITICAL` thresholds. Required only if such thresholds are configured.",
	},
	"alert_action_config": {
		Type:        schema.TypeList,
		Optional:    true,
		MaxItems:    1,
		Description: "Optional configuration applied to monitors generated by alerting thresholds.",
		Elem: &schema.Resource{
			Schema: consumptionBudgetAlertActionConfigSchema,
		},
	},
}

var consumptionBudgetAlertActionConfigSchema = map[string]*schema.Schema{
	"annotations": {
		Type:        schema.TypeMap,
		Elem:        &schema.Schema{Type: schema.TypeString},
		Optional:    true,
		Description: "Additional annotations to set on the generated monitor. Overrides the default `description`, `dashboard`, `resource`, `consumption_budget_slug`, `threshold_type`, and `partition` annotations when keys collide.",
	},
	"labels": {
		Type:        schema.TypeMap,
		Elem:        &schema.Schema{Type: schema.TypeString},
		Optional:    true,
		Description: "Additional labels to set on the generated monitor, usable for notification routing. The `resource`, `partition`, and `threshold_type` labels are reserved and cannot be overridden.",
	},
	"instant_rate_sustain_secs": {
		Type:        schema.TypeInt,
		Optional:    true,
		Description: "How long instant-rate consumption must remain above the threshold before an alert fires, in seconds. Defaults to 0 (alert immediately on any breach).",
	},
}

var consumptionBudgetPrioritySchema = map[string]*schema.Schema{
	"filter": {
		Type:        schema.TypeList,
		Optional:    true,
		Description: "Filters identifying which data matches this priority. Filters are AND-ed together: a request must match every filter to be assigned this priority.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"dataset_id": {
					Type:        schema.TypeString,
					Optional:    true,
					Description: "Deprecated: use `log_filter` instead. Slug of the dataset to match against.",
				},
				"log_filter": {
					Type:        schema.TypeList,
					Optional:    true,
					MaxItems:    1,
					Description: "Log search filter that matches log data for this priority.",
					Elem: &schema.Resource{
						Schema: LogSearchSchema,
					},
				},
			},
		},
	},
	"priority": {
		Type:        schema.TypeInt,
		Optional:    true,
		Description: "Priority order used when dropping data. Priority `10` is dropped first; priority `1` is dropped last.",
	},
}

var consumptionBudgetThresholdSchema = map[string]*schema.Schema{
	"action": Enum{
		Value:       enum.ConsumptionBudgetThresholdAction.ToStrings(),
		Optional:    true,
		Description: "Action to take when this threshold is exceeded (e.g. drop traffic, fire warning/critical alert).",
	}.Schema(),
	"type": Enum{
		Value:       enum.ConsumptionBudgetThresholdType.ToStrings(),
		Optional:    true,
		Description: "Measurement window over which the threshold is evaluated (e.g. instant rate vs. rolling volume).",
	}.Schema(),
	"instant_rate": {
		Type:        schema.TypeList,
		Optional:    true,
		MaxItems:    1,
		Description: "Configures an instant-rate threshold value. Set when `type` is an instant-rate type.",
		Elem: &schema.Resource{
			Schema: consumptionBudgetInstantRateSchema,
		},
	},
	"volume": {
		Type:        schema.TypeList,
		Optional:    true,
		MaxItems:    1,
		Description: "Configures a volume threshold value. Set when `type` is a volume type.",
		Elem: &schema.Resource{
			Schema: consumptionBudgetVolumeSchema,
		},
	},
	"sku_group": Enum{
		Value:       enum.ConsumptionBudgetSKUGroup.ToStrings(),
		Optional:    true,
		Description: "SKU group the threshold applies to (e.g. metrics, logs, traces). Replaces the deprecated top-level `resource` field.",
	}.Schema(),
	"unit": Enum{
		Value:       enum.ConsumptionBudgetUnit.ToStrings(),
		Optional:    true,
		Description: "Unit in which the threshold value is denominated (e.g. bytes, datapoints).",
	}.Schema(),
}

var consumptionBudgetInstantRateSchema = map[string]*schema.Schema{
	"fixed_value_per_sec": {
		Type:        schema.TypeInt,
		Optional:    true,
		Description: "Fixed per-second rate threshold value, expressed in the threshold's `unit`.",
	},
}

var consumptionBudgetVolumeSchema = map[string]*schema.Schema{
	"fixed_value": {
		Type:        schema.TypeInt,
		Optional:    true,
		Description: "Fixed volume threshold value, expressed in the threshold's `unit`.",
	},
}
