// Copyright 2024 Chronosphere Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package tfschema

import (
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/enum"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

var (
	sliTypes                      = []string{"sli.0.custom_indicator", "sli.0.custom_timeslice_indicator"}
	customIndicatorQueryTemplates = []string{"sli.0.custom_indicator.0.good_query_template", "sli.0.custom_indicator.0.bad_query_template"}
)

var Slo = map[string]*schema.Schema{
	"name": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Display name of the SLO. Can be changed after creation.",
	},
	"slug": {
		Type:        schema.TypeString,
		Optional:    true,
		Computed:    true,
		ForceNew:    true,
		Description: "Stable identifier for the SLO. Generated from `name` if omitted. Immutable after creation.",
	},
	"description": {
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Free-form description of the SLO.",
	},
	"collection_id": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "ID of the collection that owns this SLO.",
	},
	"notification_policy_id": {
		Type:        schema.TypeString,
		Optional:    true,
		Description: "ID of the notification policy used to route burn-rate alerts from this SLO. If omitted, the policy of the parent collection applies. Required if burn-rate alerting is enabled and the collection has no default policy.",
	},
	"sli": {
		Type:        schema.TypeList,
		Required:    true,
		MaxItems:    1,
		MinItems:    1,
		Description: "Service-level indicator (SLI) definition that produces the good/bad event ratio measured by this SLO.",
		Elem: &schema.Resource{
			Schema: SLI,
		},
	},
	"definition": {
		Type:        schema.TypeList,
		Required:    true,
		MaxItems:    1,
		MinItems:    1,
		Description: "SLO definition specifying the objective, time window, and burn-rate alerting configuration.",
		Elem: &schema.Resource{
			Schema: SloDefinition,
		},
	},
	"signal_grouping": SignalGrouping,
	"annotations": {
		Type:        schema.TypeMap,
		Optional:    true,
		Description: "Free-form key/value pairs included in notifications generated by this SLO. Templated against signal labels.",
		Elem: &schema.Schema{
			Type: schema.TypeString,
		},
	},
	"labels": {
		Type:        schema.TypeMap,
		Optional:    true,
		Description: "Key/value labels attached to the SLO. Visible in notifications and usable for routing overrides in notification policies.",
		Elem: &schema.Schema{
			Type: schema.TypeString,
		},
	},
}

var SloDefinition = map[string]*schema.Schema{
	"objective": {
		Type:        schema.TypeFloat,
		Required:    true,
		Description: "Target SLO percentage representing the desired availability (e.g. `99.9`).",
	},
	"time_window": {
		Type:        schema.TypeList,
		Optional:    true,
		Computed:    true,
		MinItems:    1,
		MaxItems:    1,
		Description: "Rolling time window over which the SLO objective is evaluated.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"duration": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Length of the evaluation window (e.g. `28d`, `24h`).",
				},
			},
		},
	},
	"burn_rate_alerting_config": {
		Type:        schema.TypeList,
		Computed:    true,
		Optional:    true,
		Description: "Custom burn-rate alert definitions. If omitted, the system default burn rates are used. Only takes effect when `enable_burn_rate_alerting` is true.",
		Elem: &schema.Resource{
			Schema: BurnRateDefinition,
		},
	},
	"enable_burn_rate_alerting": {
		Type:        schema.TypeBool,
		Optional:    true,
		Computed:    true, // This has to be computed as it's being backfilled based on other flags.
		Description: "Whether burn-rate alerting is enabled for this SLO.",
	},
}

var SLI = map[string]*schema.Schema{
	"custom_indicator": {
		Type:         schema.TypeList,
		Optional:     true,
		MaxItems:     1,
		ExactlyOneOf: sliTypes,
		Description:  "Error-ratio SLI defined by good/bad/total PromQL query templates. Mutually exclusive with `custom_timeslice_indicator`.",
		Elem: &schema.Resource{
			Schema: SloCustomIndicator,
		},
	},
	"custom_timeslice_indicator": {
		Type:         schema.TypeList,
		Optional:     true,
		MaxItems:     1,
		ExactlyOneOf: sliTypes,
		Description:  "Time-slice SLI that evaluates a PromQL query over fixed time slices against a threshold condition. Mutually exclusive with `custom_indicator`.",
		Elem: &schema.Resource{
			Schema: SloCustomTimesliceIndicator,
		},
	},
	"custom_dimension_labels": {
		Type:        schema.TypeList,
		Optional:    true,
		Description: "Additional labels exported from the underlying queries to group the error budget by. Available in PromQL templates via `{{.GroupBy}}`.",
		Elem:        &schema.Schema{Type: schema.TypeString},
	},
	"additional_promql_filters": SLOAdditionalPromQLFilters,
}

var SloCustomIndicator = map[string]*schema.Schema{
	"good_query_template": {
		Type:         schema.TypeString,
		Optional:     true,
		ExactlyOneOf: customIndicatorQueryTemplates,
		Description:  "PromQL query template measuring the count of good events. Mutually exclusive with `bad_query_template`.",
	},
	"bad_query_template": {
		Type:         schema.TypeString,
		Optional:     true,
		ExactlyOneOf: customIndicatorQueryTemplates,
		Description:  "PromQL query template measuring the count of bad events. Mutually exclusive with `good_query_template`.",
	},
	"total_query_template": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "PromQL query template measuring the total count of events. Required for error-ratio SLOs.",
	},
}

var SLOAdditionalPromQLFilters = &schema.Schema{
	Type:        schema.TypeSet,
	Optional:    true,
	Description: "Additional PromQL label matchers applied to SLI queries via the `{{.AdditionalFilters}}` template variable. Used to narrow the metrics scope.",
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"type": Enum{
				Value:       enum.PromQLMatcherType.ToStrings(),
				Required:    true,
				Description: "Matcher type (e.g. `=`, `!=`, `=~`, `!~`).",
			}.Schema(),
			"name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Prometheus label name to match.",
			},
			"value": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Label value to match against using the chosen matcher `type`.",
			},
		},
	},
}

var SloCustomTimesliceIndicator = map[string]*schema.Schema{
	"query_template": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "PromQL query template evaluated against each time slice.",
	},
	"timeslice_size": Enum{
		Value:       enum.SLITimeSliceSize.ToStrings(),
		Required:    true,
		Description: "Size of each time slice evaluated by the query (e.g. `1m`, `5m`).",
	}.Schema(),
	"condition": {
		Type:        schema.TypeList,
		Required:    true,
		MaxItems:    1,
		MinItems:    1,
		Description: "Condition used to classify each time slice as good or bad based on the query result.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"op": Enum{
					Value:       enum.ConditionOp.ToStrings(),
					Required:    true,
					Description: "Comparison operator between the query value and `value` (e.g. `gt`, `lt`, `eq`).",
				}.Schema(),
				"value": {
					Type:        schema.TypeFloat,
					Required:    true,
					Description: "Threshold value compared against the query result using `op`.",
				},
			},
		},
	},
}

var BurnRateDefinition = map[string]*schema.Schema{
	"window": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Time window for the burn-rate calculation (e.g. `1h`, `6h`).",
	},
	"budget": {
		Type:        schema.TypeFloat,
		Required:    true,
		Description: "Percentage of the error budget that can be consumed during `window` before the alert fires. Must be between 0.0 and 100.0 exclusive.",
	},
	"severity": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Severity assigned when the burn rate fires. Must be `critical` or `warn`.",
	},
	"labels": {
		Type:        schema.TypeMap,
		Optional:    true,
		Description: "Additional labels attached when this burn-rate alert fires. Can be used by notification policies to route different burn rates to different destinations.",
		Elem:        &schema.Schema{Type: schema.TypeString},
	},
}
