// Code generated by go-swagger; DO NOT EDIT.

package log_budget

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new log budget API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for log budget API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateLogBudget(params *CreateLogBudgetParams, opts ...ClientOption) (*CreateLogBudgetOK, error)

	DeleteLogBudget(params *DeleteLogBudgetParams, opts ...ClientOption) (*DeleteLogBudgetOK, error)

	ReadLogBudget(params *ReadLogBudgetParams, opts ...ClientOption) (*ReadLogBudgetOK, error)

	UpdateLogBudget(params *UpdateLogBudgetParams, opts ...ClientOption) (*UpdateLogBudgetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateLogBudget create log budget API
*/
func (a *Client) CreateLogBudget(params *CreateLogBudgetParams, opts ...ClientOption) (*CreateLogBudgetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateLogBudgetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateLogBudget",
		Method:             "POST",
		PathPattern:        "/api/unstable/config/log-budget",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateLogBudgetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateLogBudgetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateLogBudgetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteLogBudget delete log budget API
*/
func (a *Client) DeleteLogBudget(params *DeleteLogBudgetParams, opts ...ClientOption) (*DeleteLogBudgetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteLogBudgetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteLogBudget",
		Method:             "DELETE",
		PathPattern:        "/api/unstable/config/log-budget",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteLogBudgetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteLogBudgetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteLogBudgetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ReadLogBudget read log budget API
*/
func (a *Client) ReadLogBudget(params *ReadLogBudgetParams, opts ...ClientOption) (*ReadLogBudgetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReadLogBudgetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ReadLogBudget",
		Method:             "GET",
		PathPattern:        "/api/unstable/config/log-budget",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReadLogBudgetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReadLogBudgetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ReadLogBudgetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateLogBudget update log budget API
*/
func (a *Client) UpdateLogBudget(params *UpdateLogBudgetParams, opts ...ClientOption) (*UpdateLogBudgetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateLogBudgetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateLogBudget",
		Method:             "PUT",
		PathPattern:        "/api/unstable/config/log-budget",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateLogBudgetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateLogBudgetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateLogBudgetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
