// Code generated by go-swagger; DO NOT EDIT.

package log_retention_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new log retention config API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for log retention config API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateLogRetentionConfig(params *CreateLogRetentionConfigParams, opts ...ClientOption) (*CreateLogRetentionConfigOK, error)

	DeleteLogRetentionConfig(params *DeleteLogRetentionConfigParams, opts ...ClientOption) (*DeleteLogRetentionConfigOK, error)

	ListLogRetentionConfigs(params *ListLogRetentionConfigsParams, opts ...ClientOption) (*ListLogRetentionConfigsOK, error)

	ReadLogRetentionConfig(params *ReadLogRetentionConfigParams, opts ...ClientOption) (*ReadLogRetentionConfigOK, error)

	UpdateLogRetentionConfig(params *UpdateLogRetentionConfigParams, opts ...ClientOption) (*UpdateLogRetentionConfigOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateLogRetentionConfig create log retention config API
*/
func (a *Client) CreateLogRetentionConfig(params *CreateLogRetentionConfigParams, opts ...ClientOption) (*CreateLogRetentionConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateLogRetentionConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateLogRetentionConfig",
		Method:             "POST",
		PathPattern:        "/api/v1/config/log-retention-configs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateLogRetentionConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateLogRetentionConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateLogRetentionConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteLogRetentionConfig delete log retention config API
*/
func (a *Client) DeleteLogRetentionConfig(params *DeleteLogRetentionConfigParams, opts ...ClientOption) (*DeleteLogRetentionConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteLogRetentionConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteLogRetentionConfig",
		Method:             "DELETE",
		PathPattern:        "/api/v1/config/log-retention-configs/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteLogRetentionConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteLogRetentionConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteLogRetentionConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListLogRetentionConfigs list log retention configs API
*/
func (a *Client) ListLogRetentionConfigs(params *ListLogRetentionConfigsParams, opts ...ClientOption) (*ListLogRetentionConfigsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListLogRetentionConfigsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListLogRetentionConfigs",
		Method:             "GET",
		PathPattern:        "/api/v1/config/log-retention-configs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListLogRetentionConfigsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListLogRetentionConfigsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListLogRetentionConfigsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ReadLogRetentionConfig read log retention config API
*/
func (a *Client) ReadLogRetentionConfig(params *ReadLogRetentionConfigParams, opts ...ClientOption) (*ReadLogRetentionConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReadLogRetentionConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ReadLogRetentionConfig",
		Method:             "GET",
		PathPattern:        "/api/v1/config/log-retention-configs/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReadLogRetentionConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReadLogRetentionConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ReadLogRetentionConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateLogRetentionConfig update log retention config API
*/
func (a *Client) UpdateLogRetentionConfig(params *UpdateLogRetentionConfigParams, opts ...ClientOption) (*UpdateLogRetentionConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateLogRetentionConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateLogRetentionConfig",
		Method:             "PUT",
		PathPattern:        "/api/v1/config/log-retention-configs/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateLogRetentionConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateLogRetentionConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateLogRetentionConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
