// Code generated by go-swagger; DO NOT EDIT.

package log_parser_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new log parser config API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for log parser config API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateLogParserConfig(params *CreateLogParserConfigParams, opts ...ClientOption) (*CreateLogParserConfigOK, error)

	DeleteLogParserConfig(params *DeleteLogParserConfigParams, opts ...ClientOption) (*DeleteLogParserConfigOK, error)

	ReadLogParserConfig(params *ReadLogParserConfigParams, opts ...ClientOption) (*ReadLogParserConfigOK, error)

	UpdateLogParserConfig(params *UpdateLogParserConfigParams, opts ...ClientOption) (*UpdateLogParserConfigOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateLogParserConfig create log parser config API
*/
func (a *Client) CreateLogParserConfig(params *CreateLogParserConfigParams, opts ...ClientOption) (*CreateLogParserConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateLogParserConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateLogParserConfig",
		Method:             "POST",
		PathPattern:        "/api/unstable/config/log-parser-config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateLogParserConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateLogParserConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateLogParserConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteLogParserConfig delete log parser config API
*/
func (a *Client) DeleteLogParserConfig(params *DeleteLogParserConfigParams, opts ...ClientOption) (*DeleteLogParserConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteLogParserConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteLogParserConfig",
		Method:             "DELETE",
		PathPattern:        "/api/unstable/config/log-parser-config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteLogParserConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteLogParserConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteLogParserConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ReadLogParserConfig read log parser config API
*/
func (a *Client) ReadLogParserConfig(params *ReadLogParserConfigParams, opts ...ClientOption) (*ReadLogParserConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReadLogParserConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ReadLogParserConfig",
		Method:             "GET",
		PathPattern:        "/api/unstable/config/log-parser-config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReadLogParserConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReadLogParserConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ReadLogParserConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateLogParserConfig update log parser config API
*/
func (a *Client) UpdateLogParserConfig(params *UpdateLogParserConfigParams, opts ...ClientOption) (*UpdateLogParserConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateLogParserConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateLogParserConfig",
		Method:             "PUT",
		PathPattern:        "/api/unstable/config/log-parser-config",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateLogParserConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateLogParserConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateLogParserConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
