// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigUnstableUpdateSLOBody config unstable update s l o body
//
// swagger:model ConfigUnstableUpdateSLOBody
type ConfigUnstableUpdateSLOBody struct {

	// If true, the SLO will be created if it does not already exist, identified by slug. If false, an error will be returned if the SLO does not already exist.
	CreateIfMissing bool `json:"create_if_missing,omitempty"`

	// If true, the SLO will not be created nor updated, and no response SLO will be returned. The response will return an error if the given SLO is invalid.
	DryRun bool `json:"dry_run,omitempty"`

	// slo
	Slo *ConfigunstableSLO `json:"slo,omitempty"`
}

// Validate validates this config unstable update s l o body
func (m *ConfigUnstableUpdateSLOBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSlo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigUnstableUpdateSLOBody) validateSlo(formats strfmt.Registry) error {
	if swag.IsZero(m.Slo) { // not required
		return nil
	}

	if m.Slo != nil {
		if err := m.Slo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("slo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("slo")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this config unstable update s l o body based on the context it is used
func (m *ConfigUnstableUpdateSLOBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSlo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigUnstableUpdateSLOBody) contextValidateSlo(ctx context.Context, formats strfmt.Registry) error {

	if m.Slo != nil {
		if err := m.Slo.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("slo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("slo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigUnstableUpdateSLOBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigUnstableUpdateSLOBody) UnmarshalBinary(b []byte) error {
	var res ConfigUnstableUpdateSLOBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
