// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigunstableLogFieldPath configunstable log field path
//
// swagger:model configunstableLogFieldPath
type ConfigunstableLogFieldPath struct {

	// LogQL Selector to indicate field path. Use `parent[child]` syntax to
	// indicate nesting.
	Selector string `json:"selector,omitempty"`
}

// Validate validates this configunstable log field path
func (m *ConfigunstableLogFieldPath) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this configunstable log field path based on context it is used
func (m *ConfigunstableLogFieldPath) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigunstableLogFieldPath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigunstableLogFieldPath) UnmarshalBinary(b []byte) error {
	var res ConfigunstableLogFieldPath
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
