// Code generated by go-swagger; DO NOT EDIT.

package config_unstable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new config unstable API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for config unstable API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateDashboardFromClassic(params *CreateDashboardFromClassicParams, opts ...ClientOption) (*CreateDashboardFromClassicOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	CreateDashboardFromClassic Converts raw classic (Grafana) dashboard JSON to the standard dashboard

format and creates it as a standard Dashboard entity in one call.
Conversion is delegated to cloud-ui-gateway; when that service is
unavailable this endpoint fails closed with SERVICE_UNAVAILABLE.
*/
func (a *Client) CreateDashboardFromClassic(params *CreateDashboardFromClassicParams, opts ...ClientOption) (*CreateDashboardFromClassicOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateDashboardFromClassicParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateDashboardFromClassic",
		Method:             "POST",
		PathPattern:        "/api/unstable/config/dashboards:createFromClassic",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateDashboardFromClassicReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateDashboardFromClassicOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateDashboardFromClassicDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
