// Code generated by go-swagger; DO NOT EDIT.

package synthetic_global_variable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new synthetic global variable API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for synthetic global variable API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateSyntheticGlobalVariable(params *CreateSyntheticGlobalVariableParams, opts ...ClientOption) (*CreateSyntheticGlobalVariableOK, error)

	DeleteSyntheticGlobalVariable(params *DeleteSyntheticGlobalVariableParams, opts ...ClientOption) (*DeleteSyntheticGlobalVariableOK, error)

	ListSyntheticGlobalVariables(params *ListSyntheticGlobalVariablesParams, opts ...ClientOption) (*ListSyntheticGlobalVariablesOK, error)

	ReadSyntheticGlobalVariable(params *ReadSyntheticGlobalVariableParams, opts ...ClientOption) (*ReadSyntheticGlobalVariableOK, error)

	UpdateSyntheticGlobalVariable(params *UpdateSyntheticGlobalVariableParams, opts ...ClientOption) (*UpdateSyntheticGlobalVariableOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateSyntheticGlobalVariable create synthetic global variable API
*/
func (a *Client) CreateSyntheticGlobalVariable(params *CreateSyntheticGlobalVariableParams, opts ...ClientOption) (*CreateSyntheticGlobalVariableOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateSyntheticGlobalVariableParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateSyntheticGlobalVariable",
		Method:             "POST",
		PathPattern:        "/api/unstable/config/synthetic-global-variables",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateSyntheticGlobalVariableReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateSyntheticGlobalVariableOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateSyntheticGlobalVariableDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteSyntheticGlobalVariable delete synthetic global variable API
*/
func (a *Client) DeleteSyntheticGlobalVariable(params *DeleteSyntheticGlobalVariableParams, opts ...ClientOption) (*DeleteSyntheticGlobalVariableOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteSyntheticGlobalVariableParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteSyntheticGlobalVariable",
		Method:             "DELETE",
		PathPattern:        "/api/unstable/config/synthetic-global-variables/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteSyntheticGlobalVariableReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteSyntheticGlobalVariableOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteSyntheticGlobalVariableDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListSyntheticGlobalVariables list synthetic global variables API
*/
func (a *Client) ListSyntheticGlobalVariables(params *ListSyntheticGlobalVariablesParams, opts ...ClientOption) (*ListSyntheticGlobalVariablesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListSyntheticGlobalVariablesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListSyntheticGlobalVariables",
		Method:             "GET",
		PathPattern:        "/api/unstable/config/synthetic-global-variables",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListSyntheticGlobalVariablesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListSyntheticGlobalVariablesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListSyntheticGlobalVariablesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ReadSyntheticGlobalVariable read synthetic global variable API
*/
func (a *Client) ReadSyntheticGlobalVariable(params *ReadSyntheticGlobalVariableParams, opts ...ClientOption) (*ReadSyntheticGlobalVariableOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReadSyntheticGlobalVariableParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ReadSyntheticGlobalVariable",
		Method:             "GET",
		PathPattern:        "/api/unstable/config/synthetic-global-variables/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReadSyntheticGlobalVariableReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReadSyntheticGlobalVariableOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ReadSyntheticGlobalVariableDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateSyntheticGlobalVariable update synthetic global variable API
*/
func (a *Client) UpdateSyntheticGlobalVariable(params *UpdateSyntheticGlobalVariableParams, opts ...ClientOption) (*UpdateSyntheticGlobalVariableOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateSyntheticGlobalVariableParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateSyntheticGlobalVariable",
		Method:             "PUT",
		PathPattern:        "/api/unstable/config/synthetic-global-variables/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateSyntheticGlobalVariableReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateSyntheticGlobalVariableOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateSyntheticGlobalVariableDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
