// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Configv1PlaintextParserMode configv1 plaintext parser mode
//
// swagger:model configv1PlaintextParserMode
type Configv1PlaintextParserMode string

func NewConfigv1PlaintextParserMode(value Configv1PlaintextParserMode) *Configv1PlaintextParserMode {
	return &value
}

// Pointer returns a pointer to a freshly-allocated Configv1PlaintextParserMode.
func (m Configv1PlaintextParserMode) Pointer() *Configv1PlaintextParserMode {
	return &m
}

const (

	// Configv1PlaintextParserModeENABLED captures enum value "ENABLED"
	Configv1PlaintextParserModeENABLED Configv1PlaintextParserMode = "ENABLED"

	// Configv1PlaintextParserModeDISABLED captures enum value "DISABLED"
	Configv1PlaintextParserModeDISABLED Configv1PlaintextParserMode = "DISABLED"
)

// for schema
var configv1PlaintextParserModeEnum []interface{}

func init() {
	var res []Configv1PlaintextParserMode
	if err := json.Unmarshal([]byte(`["ENABLED","DISABLED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		configv1PlaintextParserModeEnum = append(configv1PlaintextParserModeEnum, v)
	}
}

func (m Configv1PlaintextParserMode) validateConfigv1PlaintextParserModeEnum(path, location string, value Configv1PlaintextParserMode) error {
	if err := validate.EnumCase(path, location, value, configv1PlaintextParserModeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this configv1 plaintext parser mode
func (m Configv1PlaintextParserMode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateConfigv1PlaintextParserModeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this configv1 plaintext parser mode based on context it is used
func (m Configv1PlaintextParserMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
