// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Configv1PlaintextParser configv1 plaintext parser
//
// swagger:model configv1PlaintextParser
type Configv1PlaintextParser struct {

	// If true, the original log will be dropped after parsing.
	// Otherwise the original log is stored under the key "plaintext_log".
	DropOriginal bool `json:"drop_original,omitempty"`

	// mode
	Mode Configv1PlaintextParserMode `json:"mode,omitempty"`

	// The name of the parser. Must be unique within the configuration.
	Name string `json:"name,omitempty"`

	// parser
	Parser *Configv1LogParser `json:"parser,omitempty"`
}

// Validate validates this configv1 plaintext parser
func (m *Configv1PlaintextParser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Configv1PlaintextParser) validateMode(formats strfmt.Registry) error {
	if swag.IsZero(m.Mode) { // not required
		return nil
	}

	if err := m.Mode.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("mode")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("mode")
		}
		return err
	}

	return nil
}

func (m *Configv1PlaintextParser) validateParser(formats strfmt.Registry) error {
	if swag.IsZero(m.Parser) { // not required
		return nil
	}

	if m.Parser != nil {
		if err := m.Parser.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parser")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parser")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this configv1 plaintext parser based on the context it is used
func (m *Configv1PlaintextParser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateParser(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Configv1PlaintextParser) contextValidateMode(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Mode.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("mode")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("mode")
		}
		return err
	}

	return nil
}

func (m *Configv1PlaintextParser) contextValidateParser(ctx context.Context, formats strfmt.Registry) error {

	if m.Parser != nil {
		if err := m.Parser.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parser")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parser")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Configv1PlaintextParser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Configv1PlaintextParser) UnmarshalBinary(b []byte) error {
	var res Configv1PlaintextParser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
