// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Configv1ServiceAttribute configv1 service attribute
//
// swagger:model configv1ServiceAttribute
type Configv1ServiceAttribute struct {

	// Created timestamp (system managed)
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Human-readable description of the service
	Description string `json:"description,omitempty"`

	// Name of the service
	Name string `json:"name,omitempty"`

	// Notification policy slug for alerts
	NotificationPolicySlug string `json:"notification_policy_slug,omitempty"`

	// Team that owns the service
	TeamSlug string `json:"team_slug,omitempty"`

	// Updated timestamp (system managed)
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this configv1 service attribute
func (m *Configv1ServiceAttribute) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Configv1ServiceAttribute) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Configv1ServiceAttribute) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this configv1 service attribute based on context it is used
func (m *Configv1ServiceAttribute) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Configv1ServiceAttribute) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Configv1ServiceAttribute) UnmarshalBinary(b []byte) error {
	var res Configv1ServiceAttribute
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
