// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LogControlRuleReplaceFieldFixedValue FixedValue is the configuration for the replace field control rule in fixed value
// mode. Used to replace the selected content with a fixed value.
//
// swagger:model LogControlRuleReplaceFieldFixedValue
type LogControlRuleReplaceFieldFixedValue struct {

	// The value to replace selected content with.
	// If empty, action will remove the content.
	Value string `json:"value,omitempty"`
}

// Validate validates this log control rule replace field fixed value
func (m *LogControlRuleReplaceFieldFixedValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this log control rule replace field fixed value based on context it is used
func (m *LogControlRuleReplaceFieldFixedValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LogControlRuleReplaceFieldFixedValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LogControlRuleReplaceFieldFixedValue) UnmarshalBinary(b []byte) error {
	var res LogControlRuleReplaceFieldFixedValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
