// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResourcePoolsAllocationFixedValue resource pools allocation fixed value
//
// swagger:model ResourcePoolsAllocationFixedValue
type ResourcePoolsAllocationFixedValue struct {

	// license
	License ResourcePoolsLicense `json:"license,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this resource pools allocation fixed value
func (m *ResourcePoolsAllocationFixedValue) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLicense(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourcePoolsAllocationFixedValue) validateLicense(formats strfmt.Registry) error {
	if swag.IsZero(m.License) { // not required
		return nil
	}

	if err := m.License.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("license")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("license")
		}
		return err
	}

	return nil
}

// ContextValidate validate this resource pools allocation fixed value based on the context it is used
func (m *ResourcePoolsAllocationFixedValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLicense(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourcePoolsAllocationFixedValue) contextValidateLicense(ctx context.Context, formats strfmt.Registry) error {

	if err := m.License.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("license")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("license")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResourcePoolsAllocationFixedValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourcePoolsAllocationFixedValue) UnmarshalBinary(b []byte) error {
	var res ResourcePoolsAllocationFixedValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
