// Code generated by go generate; DO NOT EDIT.
package intschema

import (
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/hclmarshal"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/intschema/convertintschema"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfid"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfschema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"io"
)

var _ tfid.ID // Always use tfid for simplified import generation.

type CommandCenterGroup struct {
	Name                 string                                   `intschema:"name"`
	Slug                 string                                   `intschema:"slug,optional,computed"`
	PrimarySloReference  *CommandCenterGroupPrimarySloReference   `intschema:"primary_slo_reference,optional,list_encoded_object"`
	RelatedSloReferences []CommandCenterGroupRelatedSloReferences `intschema:"related_slo_references,optional"`

	// Internal identifier used in the .state file, i.e. ResourceData.Id().
	// Cannot be set, else ToResourceData will panic.
	StateID string `intschema:"-"`

	// HCL-level identifier used in the .tf file. FromResourceData will always
	// leave this empty, and ToResourceData will panic if set.
	HCLID string `intschema:"-"`
}

func (o *CommandCenterGroup) FromResourceData(d convertintschema.ResourceGetter) error {
	return convertintschema.FromResourceData(tfschema.CommandCenterGroup, d, o)
}

func (o *CommandCenterGroup) ToResourceData(d *schema.ResourceData) diag.Diagnostics {
	return convertintschema.ToResourceData(o, d)
}

func (o *CommandCenterGroup) MarshalHCL(w io.Writer) error {
	m := hclmarshal.New()
	b := m.AddResource("chronosphere_command_center_group", o.HCLID)
	if err := hclmarshal.MarshalIntSchema(o, b); err != nil {
		return err
	}
	return m.MarshalTo(w)
}

func (o *CommandCenterGroup) Ref() tfid.ID {
	if o.HCLID == "" {
		panic("Ref is only valid when schema structs are used for marshalling")
	}

	return tfid.Ref{
		Type: "chronosphere_command_center_group",
		ID:   o.HCLID,
	}.AsID()
}

type CommandCenterGroupRelatedSloReferences struct {
	Slug string `intschema:"slug"`
}

type CommandCenterGroupPrimarySloReference struct {
	Slug string `intschema:"slug"`
}
