// Code generated by go generate; DO NOT EDIT.
package intschema

import (
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/hclmarshal"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/intschema/convertintschema"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfid"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfschema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"io"
)

var _ tfid.ID // Always use tfid for simplified import generation.

type DropRule struct {
	Name                  string                  `intschema:"name"`
	Slug                  string                  `intschema:"slug,optional,computed"`
	Query                 []string                `intschema:"query"`
	ActivatedDropDuration string                  `intschema:"activated_drop_duration,optional"`
	Active                bool                    `intschema:"active,optional,default:false"`
	ConditionalDrop       bool                    `intschema:"conditional_drop,optional"`
	DropNanValue          bool                    `intschema:"drop_nan_value,optional"`
	RateLimitThreshold    float64                 `intschema:"rate_limit_threshold,optional"`
	ValueBasedDrop        *DropRuleValueBasedDrop `intschema:"value_based_drop,optional,list_encoded_object"`

	// Internal identifier used in the .state file, i.e. ResourceData.Id().
	// Cannot be set, else ToResourceData will panic.
	StateID string `intschema:"-"`

	// HCL-level identifier used in the .tf file. FromResourceData will always
	// leave this empty, and ToResourceData will panic if set.
	HCLID string `intschema:"-"`
}

func (o *DropRule) FromResourceData(d convertintschema.ResourceGetter) error {
	return convertintschema.FromResourceData(tfschema.DropRule, d, o)
}

func (o *DropRule) ToResourceData(d *schema.ResourceData) diag.Diagnostics {
	return convertintschema.ToResourceData(o, d)
}

func (o *DropRule) MarshalHCL(w io.Writer) error {
	m := hclmarshal.New()
	b := m.AddResource("chronosphere_drop_rule", o.HCLID)
	if err := hclmarshal.MarshalIntSchema(o, b); err != nil {
		return err
	}
	return m.MarshalTo(w)
}

func (o *DropRule) Ref() tfid.ID {
	if o.HCLID == "" {
		panic("Ref is only valid when schema structs are used for marshalling")
	}

	return tfid.Ref{
		Type: "chronosphere_drop_rule",
		ID:   o.HCLID,
	}.AsID()
}

type DropRuleValueBasedDrop struct {
	TargetDropValue float64 `intschema:"target_drop_value"`
}
