// Code generated by go generate; DO NOT EDIT.
package intschema

import (
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/hclmarshal"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/intschema/convertintschema"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfid"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfschema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"io"
)

var _ tfid.ID // Always use tfid for simplified import generation.

type LogAllocationConfig struct {
	DatasetAllocation []LogAllocationConfigDatasetAllocation `intschema:"dataset_allocation,optional"`
	DefaultDataset    *LogAllocationConfigDefaultDataset     `intschema:"default_dataset,optional,list_encoded_object"`

	// Internal identifier used in the .state file, i.e. ResourceData.Id().
	// Cannot be set, else ToResourceData will panic.
	StateID string `intschema:"-"`

	// HCL-level identifier used in the .tf file. FromResourceData will always
	// leave this empty, and ToResourceData will panic if set.
	HCLID string `intschema:"-"`
}

func (o *LogAllocationConfig) FromResourceData(d convertintschema.ResourceGetter) error {
	return convertintschema.FromResourceData(tfschema.LogAllocationConfig, d, o)
}

func (o *LogAllocationConfig) ToResourceData(d *schema.ResourceData) diag.Diagnostics {
	return convertintschema.ToResourceData(o, d)
}

func (o *LogAllocationConfig) MarshalHCL(w io.Writer) error {
	m := hclmarshal.New()
	b := m.AddResource("chronosphere_log_allocation_config", o.HCLID)
	if err := hclmarshal.MarshalIntSchema(o, b); err != nil {
		return err
	}
	return m.MarshalTo(w)
}

func (o *LogAllocationConfig) Ref() tfid.ID {
	if o.HCLID == "" {
		panic("Ref is only valid when schema structs are used for marshalling")
	}

	return tfid.Ref{
		Type: "chronosphere_log_allocation_config",
		ID:   o.HCLID,
	}.AsID()
}

type LogAllocationConfigDefaultDataset struct {
	Allocation *LogAllocationConfigSchema `intschema:"allocation,optional,list_encoded_object"`
}

type LogAllocationConfigDatasetAllocation struct {
	DatasetSlug string                     `intschema:"dataset_slug"`
	Allocation  *LogAllocationConfigSchema `intschema:"allocation,optional,list_encoded_object"`
}
