// Code generated by go generate; DO NOT EDIT.
package intschema

import (
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/hclmarshal"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/intschema/convertintschema"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfid"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfschema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"io"
)

var _ tfid.ID // Always use tfid for simplified import generation.

type QueryResourcePools struct {
	DefaultPool *QueryResourcePoolsDefaultPool `intschema:"default_pool,optional,list_encoded_object"`
	Pool        []QueryResourcePoolsPool       `intschema:"pool,optional"`

	// Internal identifier used in the .state file, i.e. ResourceData.Id().
	// Cannot be set, else ToResourceData will panic.
	StateID string `intschema:"-"`

	// HCL-level identifier used in the .tf file. FromResourceData will always
	// leave this empty, and ToResourceData will panic if set.
	HCLID string `intschema:"-"`
}

func (o *QueryResourcePools) FromResourceData(d convertintschema.ResourceGetter) error {
	return convertintschema.FromResourceData(tfschema.QueryResourcePools, d, o)
}

func (o *QueryResourcePools) ToResourceData(d *schema.ResourceData) diag.Diagnostics {
	return convertintschema.ToResourceData(o, d)
}

func (o *QueryResourcePools) MarshalHCL(w io.Writer) error {
	m := hclmarshal.New()
	b := m.AddResource("chronosphere_query_resource_pools", o.HCLID)
	if err := hclmarshal.MarshalIntSchema(o, b); err != nil {
		return err
	}
	return m.MarshalTo(w)
}

func (o *QueryResourcePools) Ref() tfid.ID {
	if o.HCLID == "" {
		panic("Ref is only valid when schema structs are used for marshalling")
	}

	return tfid.Ref{
		Type: "chronosphere_query_resource_pools",
		ID:   o.HCLID,
	}.AsID()
}

type QueryResourcePoolsPool struct {
	Name          string                                `intschema:"name"`
	SourceTypes   []string                              `intschema:"source_types"`
	DataReadLimit *QueryResourcePoolDataReadLimitSchema `intschema:"data_read_limit,optional,list_encoded_object"`
	SourceNames   []string                              `intschema:"source_names,optional"`
}

type QueryResourcePoolsDefaultPool struct {
	DataReadLimit *QueryResourcePoolDataReadLimitSchema `intschema:"data_read_limit,optional,list_encoded_object"`
}
