// Code generated by go generate; DO NOT EDIT.
package intschema

import (
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/hclmarshal"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/intschema/convertintschema"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfid"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfschema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"io"
)

var _ tfid.ID // Always use tfid for simplified import generation.

type SyntheticTest struct {
	Name          string                      `intschema:"name"`
	Slug          string                      `intschema:"slug,optional,computed"`
	CollectionId  tfid.ID                     `intschema:"collection_id"`
	IntervalSecs  int64                       `intschema:"interval_secs"`
	Locations     []string                    `intschema:"locations"`
	TestType      string                      `intschema:"test_type"`
	Description   string                      `intschema:"description,optional"`
	DnsTest       *SyntheticTestDnsTest       `intschema:"dns_test,optional,list_encoded_object"`
	HttpTest      *SyntheticTestHttpTest      `intschema:"http_test,optional,list_encoded_object"`
	Labels        map[string]string           `intschema:"labels,optional"`
	MonitorConfig *SyntheticTestMonitorConfig `intschema:"monitor_config,optional,list_encoded_object"`
	RetryConfig   *SyntheticTestRetryConfig   `intschema:"retry_config,optional,list_encoded_object"`
	Status        string                      `intschema:"status,optional"`
	TcpTest       *SyntheticTestTcpTest       `intschema:"tcp_test,optional,list_encoded_object"`
	TimeoutSecs   int64                       `intschema:"timeout_secs,optional,computed"`
	TlsTest       *SyntheticTestTlsTest       `intschema:"tls_test,optional,list_encoded_object"`

	// Internal identifier used in the .state file, i.e. ResourceData.Id().
	// Cannot be set, else ToResourceData will panic.
	StateID string `intschema:"-"`

	// HCL-level identifier used in the .tf file. FromResourceData will always
	// leave this empty, and ToResourceData will panic if set.
	HCLID string `intschema:"-"`
}

func (o *SyntheticTest) FromResourceData(d convertintschema.ResourceGetter) error {
	return convertintschema.FromResourceData(tfschema.SyntheticTest, d, o)
}

func (o *SyntheticTest) ToResourceData(d *schema.ResourceData) diag.Diagnostics {
	return convertintschema.ToResourceData(o, d)
}

func (o *SyntheticTest) MarshalHCL(w io.Writer) error {
	m := hclmarshal.New()
	b := m.AddResource("chronosphere_synthetic_test", o.HCLID)
	if err := hclmarshal.MarshalIntSchema(o, b); err != nil {
		return err
	}
	return m.MarshalTo(w)
}

func (o *SyntheticTest) Ref() tfid.ID {
	if o.HCLID == "" {
		panic("Ref is only valid when schema structs are used for marshalling")
	}

	return tfid.Ref{
		Type: "chronosphere_synthetic_test",
		ID:   o.HCLID,
	}.AsID()
}

type SyntheticTestTlsTest struct {
	Host                  string                           `intschema:"host"`
	Port                  int64                            `intschema:"port"`
	AcceptSelfSigned      bool                             `intschema:"accept_self_signed,optional"`
	Assertions            []SyntheticTestTlsTestAssertions `intschema:"assertions,optional"`
	FailOnIncompleteChain bool                             `intschema:"fail_on_incomplete_chain,optional"`
	ServerName            string                           `intschema:"server_name,optional"`
}

type SyntheticTestTlsTestAssertions struct {
	CertPropertyAssertion *SyntheticTestTlsTestAssertionsCertPropertyAssertion `intschema:"cert_property_assertion,optional,list_encoded_object"`
	CertificateAssertion  *SyntheticTestTlsTestAssertionsCertificateAssertion  `intschema:"certificate_assertion,optional,list_encoded_object"`
	ResponseTimeAssertion *SyntheticResponseTimeAssertion                      `intschema:"response_time_assertion,optional,list_encoded_object"`
	TlsVersionAssertion   *SyntheticTestTlsTestAssertionsTlsVersionAssertion   `intschema:"tls_version_assertion,optional,list_encoded_object"`
}

type SyntheticTestTlsTestAssertionsTlsVersionAssertion struct {
	Bound    string `intschema:"bound"`
	Operator string `intschema:"operator"`
	Target   string `intschema:"target"`
}

type SyntheticTestTlsTestAssertionsCertificateAssertion struct {
	Operator   string `intschema:"operator"`
	TargetDays int64  `intschema:"target_days"`
}

type SyntheticTestTlsTestAssertionsCertPropertyAssertion struct {
	Operator string `intschema:"operator"`
	Property string `intschema:"property"`
	Target   string `intschema:"target"`
}

type SyntheticTestTcpTest struct {
	Host       string                           `intschema:"host"`
	Port       int64                            `intschema:"port"`
	Assertions []SyntheticTestTcpTestAssertions `intschema:"assertions,optional"`
}

type SyntheticTestTcpTestAssertions struct {
	ConnectionAssertion   *SyntheticTestTcpTestAssertionsConnectionAssertion  `intschema:"connection_assertion,optional,list_encoded_object"`
	NetworkHopsAssertion  *SyntheticTestTcpTestAssertionsNetworkHopsAssertion `intschema:"network_hops_assertion,optional,list_encoded_object"`
	ResponseTimeAssertion *SyntheticResponseTimeAssertion                     `intschema:"response_time_assertion,optional,list_encoded_object"`
}

type SyntheticTestTcpTestAssertionsNetworkHopsAssertion struct {
	Operator string `intschema:"operator"`
	Target   int64  `intschema:"target"`
}

type SyntheticTestTcpTestAssertionsConnectionAssertion struct {
	Operator string `intschema:"operator"`
	Target   string `intschema:"target"`
}

type SyntheticTestRetryConfig struct {
	MaxRetries      int64 `intschema:"max_retries,optional"`
	RetryIntervalMs int64 `intschema:"retry_interval_ms,optional,computed"`
}

type SyntheticTestMonitorConfig struct {
	NotificationPolicyId tfid.ID           `intschema:"notification_policy_id,optional"`
	Annotations          map[string]string `intschema:"annotations,optional"`
	FailingDurationSecs  int64             `intschema:"failing_duration_secs,optional"`
	MinFailingLocations  int64             `intschema:"min_failing_locations,optional"`
}

type SyntheticTestHttpTest struct {
	Method                         string                               `intschema:"method"`
	Url                            string                               `intschema:"url"`
	AllowInsecureTls               bool                                 `intschema:"allow_insecure_tls,optional"`
	Assertions                     []SyntheticTestHttpTestAssertions    `intschema:"assertions,optional"`
	Authentication                 *SyntheticTestHttpTestAuthentication `intschema:"authentication,optional,list_encoded_object"`
	ContentType                    string                               `intschema:"content_type,optional"`
	Cookies                        []SyntheticTestHttpTestCookies       `intschema:"cookies,optional"`
	DoNotSaveResponseBodyOnFailure bool                                 `intschema:"do_not_save_response_body_on_failure,optional"`
	FollowRedirects                bool                                 `intschema:"follow_redirects,optional"`
	Headers                        []SyntheticTestHttpTestHeaders       `intschema:"headers,optional"`
	HttpVersion                    string                               `intschema:"http_version,optional"`
	MaxRedirects                   int64                                `intschema:"max_redirects,optional,computed"`
	MaxResponseBodyBytes           int64                                `intschema:"max_response_body_bytes,optional"`
	QueryParams                    map[string]string                    `intschema:"query_params,optional"`
	RequestBody                    string                               `intschema:"request_body,optional"`
}

type SyntheticTestHttpTestHeaders struct {
	Name  string `intschema:"name"`
	Value string `intschema:"value"`
}

type SyntheticTestHttpTestCookies struct {
	Name  string `intschema:"name"`
	Value string `intschema:"value"`
}

type SyntheticTestHttpTestAuthentication struct {
	ApiTokenAuth                *SyntheticTestHttpTestAuthenticationApiTokenAuth                `intschema:"api_token_auth,optional,list_encoded_object"`
	BasicAuth                   *SyntheticTestHttpTestAuthenticationBasicAuth                   `intschema:"basic_auth,optional,list_encoded_object"`
	ClientCertificate           *SyntheticTestHttpTestAuthenticationClientCertificate           `intschema:"client_certificate,optional,list_encoded_object"`
	Oauth2ClientCredentials     *SyntheticTestHttpTestAuthenticationOauth2ClientCredentials     `intschema:"oauth2_client_credentials,optional,list_encoded_object"`
	Oauth2ResourceOwnerPassword *SyntheticTestHttpTestAuthenticationOauth2ResourceOwnerPassword `intschema:"oauth2_resource_owner_password,optional,list_encoded_object"`
}

type SyntheticTestHttpTestAuthenticationOauth2ResourceOwnerPassword struct {
	PasswordWo            string                 `intschema:"password_wo,write_only"`
	Username              string                 `intschema:"username"`
	ClientId              string                 `intschema:"client_id,optional"`
	ClientSecretWo        string                 `intschema:"client_secret_wo,optional,write_only"`
	ClientSecretWoVersion int64                  `intschema:"client_secret_wo_version,optional"`
	Common                *SyntheticOAuth2Common `intschema:"common,optional,list_encoded_object"`
	PasswordWoVersion     int64                  `intschema:"password_wo_version,optional"`
}

type SyntheticTestHttpTestAuthenticationOauth2ClientCredentials struct {
	ClientId              string                 `intschema:"client_id"`
	ClientSecretWo        string                 `intschema:"client_secret_wo,write_only"`
	ClientSecretWoVersion int64                  `intschema:"client_secret_wo_version,optional"`
	Common                *SyntheticOAuth2Common `intschema:"common,optional,list_encoded_object"`
}

type SyntheticTestHttpTestAuthenticationClientCertificate struct {
	Certificate         string `intschema:"certificate"`
	PrivateKeyWo        string `intschema:"private_key_wo,write_only"`
	PrivateKeyWoVersion int64  `intschema:"private_key_wo_version,optional"`
}

type SyntheticTestHttpTestAuthenticationBasicAuth struct {
	PasswordWo        string `intschema:"password_wo,write_only"`
	Username          string `intschema:"username"`
	PasswordWoVersion int64  `intschema:"password_wo_version,optional"`
}

type SyntheticTestHttpTestAuthenticationApiTokenAuth struct {
	Key            string `intschema:"key"`
	TokenWo        string `intschema:"token_wo,write_only"`
	TokenWoVersion int64  `intschema:"token_wo_version,optional"`
}

type SyntheticTestHttpTestAssertions struct {
	BodyAssertion           *SyntheticTestHttpTestAssertionsBodyAssertion           `intschema:"body_assertion,optional,list_encoded_object"`
	BodyHashAssertion       *SyntheticTestHttpTestAssertionsBodyHashAssertion       `intschema:"body_hash_assertion,optional,list_encoded_object"`
	BodyJsonPathAssertion   *SyntheticTestHttpTestAssertionsBodyJsonPathAssertion   `intschema:"body_json_path_assertion,optional,list_encoded_object"`
	BodyJsonSchemaAssertion *SyntheticTestHttpTestAssertionsBodyJsonSchemaAssertion `intschema:"body_json_schema_assertion,optional,list_encoded_object"`
	BodyXpathAssertion      *SyntheticTestHttpTestAssertionsBodyXpathAssertion      `intschema:"body_xpath_assertion,optional,list_encoded_object"`
	HeaderAssertion         *SyntheticTestHttpTestAssertionsHeaderAssertion         `intschema:"header_assertion,optional,list_encoded_object"`
	ResponseTimeAssertion   *SyntheticResponseTimeAssertion                         `intschema:"response_time_assertion,optional,list_encoded_object"`
	StatusCodeAssertion     *SyntheticTestHttpTestAssertionsStatusCodeAssertion     `intschema:"status_code_assertion,optional,list_encoded_object"`
}

type SyntheticTestHttpTestAssertionsStatusCodeAssertion struct {
	Operator string `intschema:"operator"`
	Target   string `intschema:"target"`
}

type SyntheticTestHttpTestAssertionsHeaderAssertion struct {
	Name     string `intschema:"name"`
	Operator string `intschema:"operator"`
	Target   string `intschema:"target,optional"`
}

type SyntheticTestHttpTestAssertionsBodyXpathAssertion struct {
	Operator string `intschema:"operator"`
	Xpath    string `intschema:"xpath"`
	Target   string `intschema:"target,optional"`
}

type SyntheticTestHttpTestAssertionsBodyJsonSchemaAssertion struct {
	Schema string `intschema:"schema"`
	Draft  string `intschema:"draft,optional"`
}

type SyntheticTestHttpTestAssertionsBodyJsonPathAssertion struct {
	JsonPath  string `intschema:"json_path"`
	Operator  string `intschema:"operator"`
	MatchType string `intschema:"match_type,optional"`
	Target    string `intschema:"target,optional"`
}

type SyntheticTestHttpTestAssertionsBodyHashAssertion struct {
	Algorithm string `intschema:"algorithm"`
	Target    string `intschema:"target"`
}

type SyntheticTestHttpTestAssertionsBodyAssertion struct {
	Operator string `intschema:"operator"`
	Target   string `intschema:"target"`
}

type SyntheticTestDnsTest struct {
	Domain        string                           `intschema:"domain"`
	Assertions    []SyntheticTestDnsTestAssertions `intschema:"assertions,optional"`
	DnsServer     string                           `intschema:"dns_server,optional"`
	DnsServerPort int64                            `intschema:"dns_server_port,optional"`
}

type SyntheticTestDnsTestAssertions struct {
	DnsRecordAssertion    *SyntheticTestDnsTestAssertionsDnsRecordAssertion    `intschema:"dns_record_assertion,optional,list_encoded_object"`
	ResponseTimeAssertion *SyntheticTestDnsTestAssertionsResponseTimeAssertion `intschema:"response_time_assertion,optional,list_encoded_object"`
}

type SyntheticTestDnsTestAssertionsResponseTimeAssertion struct {
	Operator string `intschema:"operator"`
	TargetMs int64  `intschema:"target_ms"`
}

type SyntheticTestDnsTestAssertionsDnsRecordAssertion struct {
	MatchScope string `intschema:"match_scope"`
	Operator   string `intschema:"operator"`
	RecordType string `intschema:"record_type"`
	Target     string `intschema:"target"`
}
