// Code generated by go generate; DO NOT EDIT.
package intschema

import (
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/hclmarshal"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/intschema/convertintschema"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfid"
	"github.com/chronosphereio/terraform-provider-chronosphere/chronosphere/tfschema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"io"
)

var _ tfid.ID // Always use tfid for simplified import generation.

type VictoropsAlertNotifier struct {
	Name                  string            `intschema:"name"`
	Slug                  string            `intschema:"slug,optional,computed"`
	ApiKey                string            `intschema:"api_key"`
	RoutingKey            string            `intschema:"routing_key"`
	ApiUrl                string            `intschema:"api_url,optional"`
	BasicAuthPassword     string            `intschema:"basic_auth_password,optional"`
	BasicAuthUsername     string            `intschema:"basic_auth_username,optional"`
	BearerToken           string            `intschema:"bearer_token,optional"`
	CustomFields          map[string]string `intschema:"custom_fields,optional"`
	EntityDisplayName     string            `intschema:"entity_display_name,optional"`
	MessageType           string            `intschema:"message_type,optional"`
	MonitoringTool        string            `intschema:"monitoring_tool,optional"`
	ProxyUrl              string            `intschema:"proxy_url,optional"`
	SendResolved          bool              `intschema:"send_resolved,optional,default:true"`
	StateMessage          string            `intschema:"state_message,optional"`
	TlsInsecureSkipVerify bool              `intschema:"tls_insecure_skip_verify,optional"`

	// Internal identifier used in the .state file, i.e. ResourceData.Id().
	// Cannot be set, else ToResourceData will panic.
	StateID string `intschema:"-"`

	// HCL-level identifier used in the .tf file. FromResourceData will always
	// leave this empty, and ToResourceData will panic if set.
	HCLID string `intschema:"-"`
}

func (o *VictoropsAlertNotifier) FromResourceData(d convertintschema.ResourceGetter) error {
	return convertintschema.FromResourceData(tfschema.VictoropsAlertNotifier, d, o)
}

func (o *VictoropsAlertNotifier) ToResourceData(d *schema.ResourceData) diag.Diagnostics {
	return convertintschema.ToResourceData(o, d)
}

func (o *VictoropsAlertNotifier) MarshalHCL(w io.Writer) error {
	m := hclmarshal.New()
	b := m.AddResource("chronosphere_victorops_alert_notifier", o.HCLID)
	if err := hclmarshal.MarshalIntSchema(o, b); err != nil {
		return err
	}
	return m.MarshalTo(w)
}

func (o *VictoropsAlertNotifier) Ref() tfid.ID {
	if o.HCLID == "" {
		panic("Ref is only valid when schema structs are used for marshalling")
	}

	return tfid.Ref{
		Type: "chronosphere_victorops_alert_notifier",
		ID:   o.HCLID,
	}.AsID()
}
