// Code generated by go-swagger; DO NOT EDIT.

package metric_name_active_series_limit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new metric name active series limit API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for metric name active series limit API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateMetricNameActiveSeriesLimit(params *CreateMetricNameActiveSeriesLimitParams, opts ...ClientOption) (*CreateMetricNameActiveSeriesLimitOK, error)

	DeleteMetricNameActiveSeriesLimit(params *DeleteMetricNameActiveSeriesLimitParams, opts ...ClientOption) (*DeleteMetricNameActiveSeriesLimitOK, error)

	ListMetricNameActiveSeriesLimits(params *ListMetricNameActiveSeriesLimitsParams, opts ...ClientOption) (*ListMetricNameActiveSeriesLimitsOK, error)

	ReadMetricNameActiveSeriesLimit(params *ReadMetricNameActiveSeriesLimitParams, opts ...ClientOption) (*ReadMetricNameActiveSeriesLimitOK, error)

	UpdateMetricNameActiveSeriesLimit(params *UpdateMetricNameActiveSeriesLimitParams, opts ...ClientOption) (*UpdateMetricNameActiveSeriesLimitOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateMetricNameActiveSeriesLimit create metric name active series limit API
*/
func (a *Client) CreateMetricNameActiveSeriesLimit(params *CreateMetricNameActiveSeriesLimitParams, opts ...ClientOption) (*CreateMetricNameActiveSeriesLimitOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateMetricNameActiveSeriesLimitParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateMetricNameActiveSeriesLimit",
		Method:             "POST",
		PathPattern:        "/api/unstable/config/metric-name-active-series-limits",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateMetricNameActiveSeriesLimitReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateMetricNameActiveSeriesLimitOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateMetricNameActiveSeriesLimitDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteMetricNameActiveSeriesLimit delete metric name active series limit API
*/
func (a *Client) DeleteMetricNameActiveSeriesLimit(params *DeleteMetricNameActiveSeriesLimitParams, opts ...ClientOption) (*DeleteMetricNameActiveSeriesLimitOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteMetricNameActiveSeriesLimitParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteMetricNameActiveSeriesLimit",
		Method:             "DELETE",
		PathPattern:        "/api/unstable/config/metric-name-active-series-limits/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteMetricNameActiveSeriesLimitReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteMetricNameActiveSeriesLimitOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteMetricNameActiveSeriesLimitDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListMetricNameActiveSeriesLimits list metric name active series limits API
*/
func (a *Client) ListMetricNameActiveSeriesLimits(params *ListMetricNameActiveSeriesLimitsParams, opts ...ClientOption) (*ListMetricNameActiveSeriesLimitsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListMetricNameActiveSeriesLimitsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListMetricNameActiveSeriesLimits",
		Method:             "GET",
		PathPattern:        "/api/unstable/config/metric-name-active-series-limits",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListMetricNameActiveSeriesLimitsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListMetricNameActiveSeriesLimitsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListMetricNameActiveSeriesLimitsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ReadMetricNameActiveSeriesLimit read metric name active series limit API
*/
func (a *Client) ReadMetricNameActiveSeriesLimit(params *ReadMetricNameActiveSeriesLimitParams, opts ...ClientOption) (*ReadMetricNameActiveSeriesLimitOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReadMetricNameActiveSeriesLimitParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ReadMetricNameActiveSeriesLimit",
		Method:             "GET",
		PathPattern:        "/api/unstable/config/metric-name-active-series-limits/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReadMetricNameActiveSeriesLimitReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReadMetricNameActiveSeriesLimitOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ReadMetricNameActiveSeriesLimitDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateMetricNameActiveSeriesLimit update metric name active series limit API
*/
func (a *Client) UpdateMetricNameActiveSeriesLimit(params *UpdateMetricNameActiveSeriesLimitParams, opts ...ClientOption) (*UpdateMetricNameActiveSeriesLimitOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateMetricNameActiveSeriesLimitParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateMetricNameActiveSeriesLimit",
		Method:             "PUT",
		PathPattern:        "/api/unstable/config/metric-name-active-series-limits/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateMetricNameActiveSeriesLimitReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateMetricNameActiveSeriesLimitOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateMetricNameActiveSeriesLimitDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
