// Code generated by go-swagger; DO NOT EDIT.

package external_connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new external connection API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for external connection API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateExternalConnection(params *CreateExternalConnectionParams, opts ...ClientOption) (*CreateExternalConnectionOK, error)

	DeleteExternalConnection(params *DeleteExternalConnectionParams, opts ...ClientOption) (*DeleteExternalConnectionOK, error)

	ListExternalConnections(params *ListExternalConnectionsParams, opts ...ClientOption) (*ListExternalConnectionsOK, error)

	ReadExternalConnection(params *ReadExternalConnectionParams, opts ...ClientOption) (*ReadExternalConnectionOK, error)

	UpdateExternalConnection(params *UpdateExternalConnectionParams, opts ...ClientOption) (*UpdateExternalConnectionOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateExternalConnection create external connection API
*/
func (a *Client) CreateExternalConnection(params *CreateExternalConnectionParams, opts ...ClientOption) (*CreateExternalConnectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateExternalConnectionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateExternalConnection",
		Method:             "POST",
		PathPattern:        "/api/v1/config/external-connections",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateExternalConnectionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateExternalConnectionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateExternalConnectionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteExternalConnection delete external connection API
*/
func (a *Client) DeleteExternalConnection(params *DeleteExternalConnectionParams, opts ...ClientOption) (*DeleteExternalConnectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteExternalConnectionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteExternalConnection",
		Method:             "DELETE",
		PathPattern:        "/api/v1/config/external-connections/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteExternalConnectionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteExternalConnectionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteExternalConnectionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListExternalConnections list external connections API
*/
func (a *Client) ListExternalConnections(params *ListExternalConnectionsParams, opts ...ClientOption) (*ListExternalConnectionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListExternalConnectionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListExternalConnections",
		Method:             "GET",
		PathPattern:        "/api/v1/config/external-connections",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListExternalConnectionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListExternalConnectionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListExternalConnectionsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ReadExternalConnection read external connection API
*/
func (a *Client) ReadExternalConnection(params *ReadExternalConnectionParams, opts ...ClientOption) (*ReadExternalConnectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReadExternalConnectionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ReadExternalConnection",
		Method:             "GET",
		PathPattern:        "/api/v1/config/external-connections/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReadExternalConnectionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReadExternalConnectionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ReadExternalConnectionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateExternalConnection update external connection API
*/
func (a *Client) UpdateExternalConnection(params *UpdateExternalConnectionParams, opts ...ClientOption) (*UpdateExternalConnectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateExternalConnectionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateExternalConnection",
		Method:             "PUT",
		PathPattern:        "/api/v1/config/external-connections/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateExternalConnectionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateExternalConnectionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateExternalConnectionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
