// Package localid is used to create fake IDs used for Terraform resources not managed on the server.
package localid

import (
	"fmt"
	"math/rand"
	"regexp"
	"sync"
	"time"
)

var (
	// localPolicyIDRegex is the pattern for Terraform state IDs that were generated by this provider and not the server.
	// There are in the form of an INT, local-INT, or imported-INT: "12345", "local-12345", "imported-12345".
	// NB: while the latest provider uses "local-INT" format, older versions used just "INT".
	localPolicyIDRegex = regexp.MustCompile(`^((local|imported)-)?\d+$`)

	mu         sync.Mutex
	randSource = rand.NewSource(time.Now().UnixNano())
)

// IsLocalID returns whether an ID was generated by this package.
func IsLocalID(id string) bool {
	return localPolicyIDRegex.MatchString(id)
}

// NewLocalID generates a random local id.
func NewLocalID() string {
	return prefixedID("local")
}

// NewImportedID generates a random local id.
func NewImportedID() string {
	return prefixedID("imported")
}

func prefixedID(prefix string) string {
	mu.Lock()
	defer mu.Unlock()

	return fmt.Sprintf("%s-%d", prefix, randSource.Int63())
}
