// Code generated by go-swagger; DO NOT EDIT.

package log_primary_key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new log primary key API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for log primary key API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateLogPrimaryKey(params *CreateLogPrimaryKeyParams, opts ...ClientOption) (*CreateLogPrimaryKeyOK, error)

	DeleteLogPrimaryKey(params *DeleteLogPrimaryKeyParams, opts ...ClientOption) (*DeleteLogPrimaryKeyOK, error)

	ListLogPrimaryKeys(params *ListLogPrimaryKeysParams, opts ...ClientOption) (*ListLogPrimaryKeysOK, error)

	ReadLogPrimaryKey(params *ReadLogPrimaryKeyParams, opts ...ClientOption) (*ReadLogPrimaryKeyOK, error)

	UpdateLogPrimaryKey(params *UpdateLogPrimaryKeyParams, opts ...ClientOption) (*UpdateLogPrimaryKeyOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateLogPrimaryKey create log primary key API
*/
func (a *Client) CreateLogPrimaryKey(params *CreateLogPrimaryKeyParams, opts ...ClientOption) (*CreateLogPrimaryKeyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateLogPrimaryKeyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateLogPrimaryKey",
		Method:             "POST",
		PathPattern:        "/api/unstable/config/log-primary-keys",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateLogPrimaryKeyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateLogPrimaryKeyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateLogPrimaryKeyDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteLogPrimaryKey delete log primary key API
*/
func (a *Client) DeleteLogPrimaryKey(params *DeleteLogPrimaryKeyParams, opts ...ClientOption) (*DeleteLogPrimaryKeyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteLogPrimaryKeyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteLogPrimaryKey",
		Method:             "DELETE",
		PathPattern:        "/api/unstable/config/log-primary-keys/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteLogPrimaryKeyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteLogPrimaryKeyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteLogPrimaryKeyDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListLogPrimaryKeys list log primary keys API
*/
func (a *Client) ListLogPrimaryKeys(params *ListLogPrimaryKeysParams, opts ...ClientOption) (*ListLogPrimaryKeysOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListLogPrimaryKeysParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListLogPrimaryKeys",
		Method:             "GET",
		PathPattern:        "/api/unstable/config/log-primary-keys",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListLogPrimaryKeysReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListLogPrimaryKeysOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListLogPrimaryKeysDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ReadLogPrimaryKey read log primary key API
*/
func (a *Client) ReadLogPrimaryKey(params *ReadLogPrimaryKeyParams, opts ...ClientOption) (*ReadLogPrimaryKeyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReadLogPrimaryKeyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ReadLogPrimaryKey",
		Method:             "GET",
		PathPattern:        "/api/unstable/config/log-primary-keys/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReadLogPrimaryKeyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReadLogPrimaryKeyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ReadLogPrimaryKeyDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateLogPrimaryKey update log primary key API
*/
func (a *Client) UpdateLogPrimaryKey(params *UpdateLogPrimaryKeyParams, opts ...ClientOption) (*UpdateLogPrimaryKeyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateLogPrimaryKeyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateLogPrimaryKey",
		Method:             "PUT",
		PathPattern:        "/api/unstable/config/log-primary-keys/{slug}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateLogPrimaryKeyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateLogPrimaryKeyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateLogPrimaryKeyDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
